'use strict';
const { tokenize } = require('./tokenizer');
const unsupported = (construct, position) => ({ ok: false, rejection: { code: 'unsupported-construct', construct, position, message: `${construct} is not supported`, hint: 'Simplify the SQL or use queries.excel_power_query for raw M.' } });

function parseSql(sql, options) {
  try { return new Parser(sql, options).parse(); } catch (error) { return error && error.rejection ? { ok: false, rejection: error.rejection } : unsupported('Invalid SQL', 0); }
}
class Parser {
  constructor(sql, options) { this.tokens = tokenize(sql); this.i = 0; this.options = options || {}; }
  t(n = 0) { return this.tokens[this.i + n]; } word(x) { return this.t().type === 'word' && this.t().value.toUpperCase() === x; }
  fail(construct, token = this.t(), message, hint) { const e = new Error(message || construct); e.rejection = { code: 'unsupported-construct', construct, position: token.position, message: message || `${construct} is not supported`, hint: hint || 'Simplify the SQL or use queries.excel_power_query for raw M.' }; throw e; }
  eat(x) { const t = this.t(); if (t.value.toUpperCase() !== x.toUpperCase()) this.fail(`Expected ${x}`, t, `Expected ${x}`); this.i += 1; return t; }
  ident() { const t = this.t(); if (!['word', 'identifier'].includes(t.type)) this.fail('Identifier', t, 'Expected an identifier'); this.i += 1; return t.value; }
  parse() {
    if (this.word('WITH')) this.fail('CTEs (WITH)', this.t(), undefined, 'Rewrite the CTE as a subquery in FROM: SELECT ... FROM (<cte body>) x ... — subqueries are the supported staging mechanism.'); const first = this.select(); const arms = [first]; const unions = [];
    while (this.word('UNION')) { this.i++; const all = this.word('ALL'); if (all) this.i++; unions.push({ all }); arms.push(this.select()); }
    if (this.t().type !== 'eof' && this.t().value !== ';') this.fail(this.t().value.toUpperCase());
    if (arms.length > 1) return { ok: true, ast: { type: 'union', arms, unions } };
    return { ok: true, ast: first };
  }
  select() {
    if (!this.word('SELECT')) this.fail('SELECT statement'); this.eat('SELECT'); const distinct = this.word('DISTINCT'); if (distinct) this.i += 1;
    const select = []; do { if (this.t().value === '*') { this.i++; select.push({ type: 'star', position: this.t(-1).position }); } else select.push(this.item()); if (this.t().value !== ',') break; this.i++; } while (true);
    this.eat('FROM'); const from = this.table(); const joins = [];
    while (this.word('LEFT') || this.word('INNER') || this.word('RIGHT') || this.word('FULL') || this.word('CROSS') || this.word('JOIN')) {
      let kind = 'INNER'; if (!this.word('JOIN')) { kind = this.ident().toUpperCase(); if (this.word('OUTER')) this.i++; } if (kind === 'RIGHT') this.fail('RIGHT JOIN'); this.eat('JOIN'); const table = this.table(); const on = kind === 'CROSS' ? null : (this.eat('ON'), this.expr()); joins.push({ kind, table, on });
    }
    let where = null; if (this.word('WHERE')) { this.i++; where = this.expr(); }
    let groupBy = []; if (this.word('GROUP')) { this.i++; this.eat('BY'); groupBy = this.list(() => this.expr()); }
    let having = null; if (this.word('HAVING')) { this.i++; having = this.expr(); }
    let orderBy = []; if (this.word('ORDER')) { this.i++; this.eat('BY'); orderBy = this.list(() => { const expression = this.expr(); const direction = this.word('DESC') ? (this.i++, 'DESC') : (this.word('ASC') ? (this.i++, 'ASC') : 'ASC'); return { expression, direction }; }); }
    if (this.word('LIMIT')) this.fail('LIMIT', this.t(), undefined, "ORDER BY plus the report's row/paging layout handles top-N presentation; LIMIT/OFFSET are not supported in compiled SQL. Use raw M in queries.excel_power_query if you need it."); if (this.word('OFFSET')) this.fail('OFFSET', this.t(), undefined, "ORDER BY plus the report's row/paging layout handles top-N presentation; LIMIT/OFFSET are not supported in compiled SQL. Use raw M in queries.excel_power_query if you need it.");
    if (joins.some(j => !j.table.subquery && !from.subquery && j.table.name.toLowerCase() === from.name.toLowerCase())) this.fail('self-joins', { position: from.position });
    return { type: 'select', distinct, select, from, joins, where, groupBy, having, orderBy };
  }
  table() { const position = this.t().position; if (this.t().value === '(') { this.i++; const subquery = this.select(); this.eat(')'); let alias; if (this.word('AS')) this.i++; alias = this.ident(); return { name: alias, alias, position, subquery }; } const name = this.ident(); let alias = name; if (this.word('AS')) { this.i++; alias = this.ident(); } else if (['word', 'identifier'].includes(this.t().type) && !['ON','LEFT','INNER','RIGHT','FULL','CROSS','WHERE','GROUP','HAVING','ORDER','JOIN','LIMIT','OFFSET','UNION'].includes(this.t().value.toUpperCase())) alias = this.ident(); return { name, alias, position }; }
  item() { const position = this.t().position; const expression = this.expr(); let alias = null; if (this.word('AS')) { this.i++; alias = this.ident(); } else if (['word','identifier'].includes(this.t().type) && !['FROM','WHERE','GROUP','HAVING','ORDER','LEFT','INNER','RIGHT','FULL','CROSS','JOIN'].includes(this.t().value.toUpperCase())) alias = this.ident(); return { expression, alias: alias || this.defaultName(expression), position }; }
  defaultName(e) { return e.type === 'column' ? e.name : e.type === 'call' ? e.name : 'Expression'; }
  list(fn) { const out = [fn()]; while (this.t().value === ',') { this.i++; out.push(fn()); } return out; }
  expr(min = 0) { let left = this.prefix(); const prec = { OR: 1, AND: 2, '=': 3, '!=': 3, '<>': 3, '<': 3, '>': 3, '<=': 3, '>=': 3, '+': 4, '-': 4, '||': 4, '*': 5, '/': 5 };
    while (true) { let op = this.t().value.toUpperCase(); if (op === 'OVER') this.fail('window functions (OVER)'); if (op === 'IS') { if (3 < min) break; this.i++; const not = this.word('NOT'); if (not) this.i++; this.eat('NULL'); left = { type: 'isnull', expression: left, not }; continue; } if (op === 'IN' || (op === 'NOT' && this.t(1).value.toUpperCase() === 'IN')) { if (3 < min) break; const negated = op === 'NOT'; this.i += negated ? 2 : 1; this.eat('('); if (this.word('SELECT')) this.fail('IN (SELECT)'); const values = this.list(() => this.expr()); this.eat(')'); left = { type: 'in', expression: left, values, negated }; continue; } if (op === 'BETWEEN') { if (3 < min) break; this.i++; const low = this.expr(3); this.eat('AND'); const high = this.expr(3); left = { type: 'between', expression: left, low, high }; continue; } if (op === 'LIKE') this.fail(op, this.t(), undefined, 'Use = or IN (...) instead of LIKE where possible; LIKE is not supported.'); if (op === 'GLOB') this.fail(op); const p = prec[op]; if (!p || p < min) break; this.i++; left = { type: 'binary', op, left, right: this.expr(p + 1) }; } return left; }
  prefix() { const t = this.t(); const exists = negated => { const position = this.t().position; this.eat('EXISTS'); this.eat('('); if (!this.word('SELECT')) this.fail('EXISTS subquery', this.t(), 'EXISTS requires a SELECT subquery'); const subquery = this.select(); this.eat(')'); return { type: 'exists', negated, subquery, position }; }; if (this.word('NOT')) { this.i++; if (this.word('EXISTS')) return exists(true); return { type: 'unary', op: 'NOT', expression: this.expr(3) }; } if (this.word('EXISTS')) return exists(false); if (t.type !== 'string' && (t.value === '-' || t.value === '+')) { this.i++; return { type: 'unary', op: t.value, expression: this.expr(6) }; } if (this.word('CASE')) return this.caseExpr(); if (t.type === 'string') { this.i++; return { type: 'literal', value: t.value, literalType: 'string' }; } if (t.type === 'number') { this.i++; return { type: 'literal', value: Number(t.value), literalType: 'number' }; } if (this.word('NULL')) { this.i++; return { type: 'literal', value: null, literalType: 'null' }; } if (t.value === '(') { this.i++; const x = this.expr(); this.eat(')'); return x; } const name = this.ident(); if (this.t().value === '(') { this.i++; if (name.toUpperCase() === 'CAST') { const value = this.expr(); this.eat('AS'); const asType = this.ident(); this.eat(')'); return { type: 'cast', value, asType }; } const args = this.t().value === ')' ? [] : this.list(() => { if (this.t().value === '*') { this.i++; return { type: 'star' }; } if (this.word('DISTINCT')) { this.i++; return { type: 'call', name: 'DISTINCT', args: [this.expr()] }; } return this.expr(); }); this.eat(')'); return { type: 'call', name: name.toUpperCase(), args }; } let table = null; let column = name; if (this.t().value === '.') { this.i++; table = name; column = this.ident(); } return { type: 'column', table, name: column }; }
  caseExpr() { this.eat('CASE'); const branches = []; while (this.word('WHEN')) { this.i++; const when = this.expr(); this.eat('THEN'); branches.push({ when, then: this.expr() }); } let otherwise = { type: 'literal', value: null, literalType: 'null' }; if (this.word('ELSE')) { this.i++; otherwise = this.expr(); } this.eat('END'); return { type: 'case', branches, otherwise }; }
}
module.exports = { parseSql };
