'use strict';
const hint = 'EXISTS supports exactly one correlated equality condition in a top-level AND; for more complex correlation, write the anti-join manually: LEFT JOIN (SELECT DISTINCT ...) x ON ... WHERE x.col IS [NOT] NULL — see docs/excel-report-sql-patterns.md.';
const reject = (construct, position, message) => ({ ok: false, rejection: { code: 'unsupported-construct', construct, position: position == null ? 0 : position, message, hint } });
const ands = e => e && e.type === 'binary' && e.op === 'AND' ? ands(e.left).concat(ands(e.right)) : [e];
const chain = xs => xs.reduce((left, right) => left ? { type: 'binary', op: 'AND', left, right } : right, null);
const hasExists = e => Boolean(e && typeof e === 'object' && (e.type === 'exists' || Object.values(e).some(v => Array.isArray(v) ? v.some(hasExists) : hasExists(v))));
const firstExists = e => !e || typeof e !== 'object' ? null : e.type === 'exists' ? e : Object.values(e).flatMap(v => Array.isArray(v) ? v : [v]).map(firstExists).find(Boolean);
const outerReference = (e, aliases) => Boolean(e && typeof e === 'object' && (e.type === 'column' && e.table && aliases.has(String(e.table).toLowerCase()) || Object.values(e).some(v => Array.isArray(v) ? v.some(x => outerReference(x, aliases)) : outerReference(v, aliases))));
function rewriteExists(ast) {
  if (ast.type === 'union') { const exists = ast.arms.map(arm => firstExists(arm.where)).find(Boolean); return exists ? reject('EXISTS inside UNION', exists.position, 'EXISTS inside UNION is not supported; rewrite each UNION arm using an explicit anti-join.') : { ok: true, ast }; }
  if (!hasExists(ast.where)) return { ok: true, ast };
  const outerAliases = new Set([ast.from.alias, ...ast.joins.map(j => j.table.alias)].map(x => String(x).toLowerCase())); const aliases = new Set(outerAliases); const terms = ands(ast.where);
  for (const term of terms) if (term.type !== 'exists' && hasExists(term)) return reject('EXISTS under OR', firstExists(term).position, 'EXISTS under OR is not supported; use an explicit anti-join so the boolean grouping remains clear.');
  for (let i = 0; i < terms.length; i++) if (terms[i].type === 'exists') { const exists = terms[i]; const sub = exists.subquery; if (sub.joins.length > 1 || !sub.where || sub.groupBy.length || sub.having || sub.orderBy.length || sub.select.length !== 1 || sub.select[0].expression.type !== 'literal' || sub.select[0].expression.value !== 1) return reject('EXISTS subquery shape', exists.position, 'EXISTS requires SELECT 1 FROM one inner table with a WHERE clause.'); const innerAlias = String(sub.from.alias).toLowerCase(); const innerTerms = ands(sub.where); const matches = innerTerms.filter(x => x && x.type === 'binary' && x.op === '=' && x.left && x.left.type === 'column' && x.right && x.right.type === 'column' && x.left.table && x.right.table && ((outerAliases.has(String(x.left.table).toLowerCase()) && String(x.right.table).toLowerCase() === innerAlias) || (outerAliases.has(String(x.right.table).toLowerCase()) && String(x.left.table).toLowerCase() === innerAlias))); if (matches.length !== 1) return reject('EXISTS correlation', exists.position, 'EXISTS requires exactly one qualified equality between the inner table alias and an outer table alias.'); const equality = matches[0]; const innerColumn = String(equality.left.table).toLowerCase() === innerAlias ? equality.left : equality.right; const outerColumn = innerColumn === equality.left ? equality.right : equality.left; const remainder = innerTerms.filter(x => x !== equality); if (remainder.some(x => outerReference(x, outerAliases)) || sub.joins.some(join => outerReference(join.on, outerAliases))) return reject('EXISTS correlation', exists.position, 'EXISTS supports only one correlated equality; remaining inner conditions must reference only the inner table.'); let n = 1; while (aliases.has(`__exists_${n}`.toLowerCase())) n++; const alias = `__exists_${n}`; const key = innerColumn.name; const innerSelect = { type: 'column', table: sub.from.alias, name: key }; const subquery = { type: 'select', distinct: true, select: [{ expression: innerSelect, alias: key, position: exists.position }], from: sub.from, joins: sub.joins, where: chain(remainder), groupBy: [], having: null, orderBy: [] }; ast.joins.push({ kind: 'LEFT', table: { name: alias, alias, position: exists.position, subquery }, on: { type: 'binary', op: '=', left: { type: 'column', table: alias, name: key }, right: { type: 'column', table: outerColumn.table, name: outerColumn.name } } }); terms[i] = { type: 'isnull', expression: { type: 'column', table: alias, name: key }, not: !exists.negated }; aliases.add(alias.toLowerCase()); }
  ast.where = chain(terms); return { ok: true, ast };
}
module.exports = { rewriteExists };
